SportsStore/SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart? Cart { get; set; }
        public string? ReturnUrl { get; set; }
    }
}

SportsStore/SportsStore.WebUI/Models/ErrorViewModel.cs
namespace SportsStore.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SportsStore/SportsStore.WebUI/Models/PagingInfo.cs
namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

SportsStore/SportsStore.WebUI/Models/ProductsListViewModel.cs
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product>? Products { get; set; }
        public PagingInfo? PagingInfo { get; set; }
        public string? CurrentCategory { get; set; }
    }
}

SportsStore/SportsStore.WebUI/Components/NavPartialViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Interfaces;

namespace SportsStore.WebUI.Components
{
    public class NavPartialViewComponent : ViewComponent
    {
        private readonly IProductRepository _repository;
        public NavPartialViewComponent(IProductRepository repo)
        {
            _repository = repo;
        }

        public IViewComponentResult Invoke(string? category)
        {
            ViewData["SelectedCategory"] = category;            
            var categories = _repository.Products.Select(p => p.Category).Distinct().OrderBy(c => c);
            return View("_Menu", categories);
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Entities;
using SportsStore.Domain.Interfaces;
using SportsStore.WebUI.Binders;
using SportsStore.WebUI.Extensions;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        public CartController(IProductRepository repo)
        {
            _repository = repo;
        }

        public IActionResult Index([ModelBinder(typeof(CartModelBinder))] Cart cart, string returnUrl)
        {
            var model = new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl };
            return View(model);
        }

        public IActionResult AddToCart([ModelBinder(typeof(CartModelBinder))] Cart cart, int productId, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
                HttpContext.Session.Set("Cart", cart);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public IActionResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            var product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.WebUI.Models;
using System.Diagnostics;

namespace SportsStore.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Domain.Interfaces;
using SportsStore.WebUI.Models;
using System.Diagnostics;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _repository;
        public int PageSize = 4;


        public ProductController(IProductRepository repository)
        {      
            _repository = repository;      
        }

        public IActionResult List(string category, int page = 1)
        {       
            var model = new ProductsListViewModel
            {
                Products = _repository.Products
                .Where(p => category == null || p.Category == category)
            .OrderBy(p => p.ProductId)
            .Skip((page - 1) * PageSize)
            .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    _repository.Products.Count() :
                    _repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SportsStore/SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "SportsStore: Your Cart";
}

<h2>Your cart</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">Quantity</th>
            <th align="center">Item</th>
            <th align="center">Price</th>
            <th align="center">Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var line in Model.Cart?.Lines!)
        {
            <tr>
                <td align="center">@line.Quantity</td>
                <td align="left">@line.Product?.Name</td>
                <td align="right">@line.Product?.Price?.ToString("c")</td>
                <td align="right">@((line.Quantity * line.Product?.Price ?? 0).ToString("c"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Total:</td>
            <td align="right">
                @Model.Cart.ComputeTotalValue()?.ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Continue shopping</a>
</p>

SportsStore/SportsStore.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SportsStore/SportsStore.WebUI/Views/Product/List.cshtml
@using SportsStore.WebUI.HtmlHelpers
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
    ViewData["Title"] = "Product List";
}

@foreach (var product in Model.Products!)
{
   await Html.RenderPartialAsync("_ProductSummary", product);
}

<div class="pager">
    @Html.PagingLinks(Model.PagingInfo!, x => Url.Action("List", new { page = x, category = Model.CurrentCategory })!)
</div>

SportsStore/SportsStore.WebUI/Views/Shared/Components/NavPartial/_Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product")

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Product",
        action = "List",
        category = link,
        page = 1
    },
    new
    {
        @class = link == ViewData["SelectedCategory"]?.ToString() ? "selected" : null
    })
}

SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportsStore.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportsStore.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="header">
        <h1 class="title">Sports store</h1>
    </header>

    <div class="categories">
        @await Component.InvokeAsync("NavPartial", new { category = ViewContext.RouteData.Values["category"] })
    </div>

    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SportsStore.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SportsStore/SportsStore.WebUI/Views/Shared/_ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        @Html.HiddenFor(x => x.ProductId)
        @Html.Hidden("returnUrl", @Context.Request.Path + @Context.Request.QueryString)
        <input type="submit" value="+ Add to cart" />
    }

    <h4>@Model.Price?.ToString("c")</h4>
</div>